# -*- coding: utf-8 -*-
"""Osteo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUq1dZ51Yi6_9R2dtxYjCyLaZr-eMkNI
"""

from google.colab import files
import zipfile
import os

uploaded = files.upload()


with zipfile.ZipFile("/content/OSTEO.zip", 'r') as zip_ref:
    zip_ref.extractall("Fotos")

folder_path = "Fotos/"

m, n = 128, 128

images = []
image_names = []
image_paths = []

for path in imagenes:
    img = Image.open(path).convert("RGB")
    img = img.resize((n, m))
    img_array = np.array(img).transpose(2,0,1)

    images.append(img_array)
    image_names.append(os.path.basename(path))
    image_paths.append(path)

images = np.array(images)

print("Shape final:", images.shape)
print("Ejemplo de nombres:", image_names[:5])

import matplotlib.pyplot as plt

fig, axes = plt.subplots(3, 3, figsize=(6,6))

for i, ax in enumerate(axes.flat):
    if i < len(images):
        img = images[i].transpose(1, 2, 0)  # volver a (m, n, 3)
        ax.imshow(img)
        ax.axis("off")

plt.tight_layout()
plt.show()

import pandas as pd
tabla = pd.read_excel("/content/Fotos/Datos/BASE_OSTEO_50.xlsx")
print(tabla.head())

# Ver un ejemplo de IDs en la tabla
print(tabla["ID"].head(10))

# Ver un ejemplo de claves en el diccionario de imágenes
print(list(imagenes_dict.keys())[:10])

import os


imagenes_dict = {os.path.splitext(os.path.basename(path))[0]: img for path, img in zip(imagenes, images)}


tabla["matriz"] = tabla["ID"].map(imagenes_dict)


print("Coincidencias:", tabla["matriz"].notna().sum(), "de", len(tabla))

import matplotlib.pyplot as plt

fig, axes = plt.subplots(3, 3, figsize=(8,8))
for i, ax in enumerate(axes.flat):
    img = tabla.iloc[i]["matriz"].transpose(1, 2, 0)  # (128,128,3)
    ax.imshow(img.astype("uint8"))
    ax.set_title(tabla.iloc[i]["ID"])
    ax.axis("off")
plt.tight_layout()
plt.show()

tabla.to_pickle("tabla_con_imagenes.pkl")

tabla.to_pickle("dataset_osteo.pkl")

import pandas as pd
tabla = pd.read_pickle("dataset_osteo.pkl")
print(tabla.head())